version: '3.8'  # Specify the version of the Docker Compose file format

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydevcontainer
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/code
    networks:
      - auth-network  # Ensure this is properly indented under 'api'

networks:
  auth-network:
    driver: bridge  # Optional, but you can specify the network driver if needed








# name: "fastapi"
# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: mydevcontainer
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./auth_service:/code
#   networks:
#   - auth-network
# networks:
#   auth-network:


# version: '3.8'

# services:
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
